# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

DISABLE_LINTERS:
  - JAVA_PMD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - SQL_TSQLLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER

GROOVY_NPM_GROOVY_LINT_ARGUMENTS:
  - "--failon=warning"

REPOSITORY_TRIVY_ARGUMENTS:
  - "--severity=MEDIUM,HIGH,CRITICAL"
  - "--ignore-unfixed"

JAVA_CHECKSTYLE_CONFIG_FILE: .checkstyle/checkstyle.xml

MARKDOWN_MARKDOWN_TABLE_FORMATTER_ARGUMENTS:
  - "--columnpadding 1"

REPOSITORY_KICS_ARGUMENTS:
  - --fail-on=HIGH
